### PR TITLE
NF pool

### PR DESCRIPTION
**Pull request by dennisafa**
This PR implements a NF pool API. 

## Summary:
This PR allows developers to create add and remove NF's from a pool. The pool is a hashmap that maps an NF to a pool context structure, which holds a ring of initialized network functions. Developers can add/remove from the pool by using the enqueue/dequeue function calls. Adding to the pool means instantiating a new NF and storing its NF struct pointer within a ring. Dequeueing will remove from the ring and intialize the network function. When an NF is added to the pool, it is put to sleep on a semaphore. The semaphore is then posted to when a dequeue occurs. This is very similar to the shared core functionality that we already have. 

**Usage:**
I will be uploading a sample NF that shows usage of the pool API. It can be used from any network function, probably one that needs to do loadbalancing or just needs duplicate NF's that must be activated in a time sensitive manner. 

| This PR includes         |          |
| ------------------------ | -------- |
| Resolves issues          |  
| Breaking API changes     |
| Internal API changes     | X
| Usability improvements   |  
| Bug fixes                |
| New functionality        | X
| New NF/onvm_mgr args     | 
| Changes to starting NFs  |  
| Dependency updates       | 
| Web stats updates        | 

## Merging notes:
 - Dependencies: None  

**TODO before merging :**
 - [ ] PR is ready for review
 - [ ] Documentation (probably a wiki page or something)
 - [ ] Sample NF (probably gonna use the scaling NF and repurpose it)
 - [ ] Figure out what to do about NF args. 

## Test Plan:
The big thing we need to figure out is how to parse NF args. Right now the enqueue function takes a struct argument that contains args for the NF being instantiated. Im thinking of doing some sort of JSON implementation of this. Discuss below on what you think is best

## Review: 
Anyone. This is a good chunk of new functionality.

### CODE REVIEW

**Comment by onvm** [comment]
> In response to PR creation

## CI Message

Your results will arrive shortly

File: onvm/onvm_nflib/onvm_nflib.c [hunk 1]
```diff
@@ -1386,3 +1500,265 @@ onvm_nflib_stats_summary_output(uint16_t id) {
...
+                return NULL;
+        }
+        if (nf_args == NULL) {
+                RTE_LOG(INFO, APP, "onvm_nflib_fork(): nf_args is null\n");
+                return NULL;
+        }
+
+        instance_id = onvm_nflib_request_next_instance_id();
+        binary_string = onvm_nflib_create_binary_exec_string(nf_name);
+        if (fork() == 0) {
```
Comment (koolzz) [inline onvm/onvm_nflib/onvm_nflib.c:1658]: Yeahhhh so this whole hard coded arg thing just seems hacky even without reading too much into it. Can you explain what we're trying to achieve here

Comment (dennisafa) [reply onvm/onvm_nflib/onvm_nflib.c:1658]: It is hacky and should be more automated and clean. The idea is that each NF gets its executable path,and then we do an execl to load that process, starting the NF. Getting the args to the Nf's isn't straightforward - in this case a struct is used to hold the arguments to the Nf. A user can specify many combinations of the arguments and thats why this branch is so long. This could be replaced with something like calling a shell script from the C code to let it do the messy business of starting the NF.

**Comment by dennisafa** [comment]
have been slammed with work. I'll try to get this improved this coming weekend.

File: onvm/onvm_nflib/onvm_nflib.c (hunk 1 above)
Comment (koolzz) [reply onvm/onvm_nflib/onvm_nflib.c:1658]: Okay stick something info the nf infromation which identifies the execl format string and define the rqeuired args for it. That was we can be NF agnostic in this

Comment (dennisafa) [reply onvm/onvm_nflib/onvm_nflib.c:1658]: I refactored to directly call the NF bash script.

**Comment by dennisafa** [comment]
I know you are all slammed but if you have time give this a look.

File: onvm/onvm_nflib/onvm_nflib.c [hunk 2]
```diff
@@ -1411,3 +1525,239 @@ onvm_nflib_stats_summary_output(uint16_t id) {
...
+                RTE_LOG(INFO, APP, "Could not extract current working CWD");
+                return NULL;
+        }
+
+        token = strstr(cwd, examples_path);
+        *token = '\0';
+        token_len = strlen(token);
+        cwd = cwd + token_len;
+
+        cwd_len = strlen(cwd);
```
Comment (WilliamMaa) [inline onvm/onvm_nflib/onvm_nflib.c:1720]: I got a compile error on this specific line. 

In file included from /usr/include/string.h:495,                                                                                                              
                 from /local/onvm/openNetVM/onvm/onvm_nflib/onvm_includes.h:62,                                                                               
                 from /local/onvm/openNetVM/onvm/onvm_nflib/onvm_nflib.c:56:                                                                                  
In function ‘strncat’,                                                                                                                                        
    inlined from ‘onvm_nflib_get_go_script_path’ at /local/onvm/openNetVM/onvm/onvm_nflib/onvm_nflib.c:1721:9:                                                
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:136:10: error: ‘__builtin_strncat’ output truncated before terminating nul copying as many bytes from a 
string as its length [-Werror=stringop-truncation]
  136 |   return __builtin___strncat_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/local/onvm/openNetVM/onvm/onvm_nflib/onvm_nflib.c: In function ‘onvm_nflib_get_go_script_path’:                                                              
/local/onvm/openNetVM/onvm/onvm_nflib/onvm_nflib.c:1715:19: note: length computed here
 1715 |         cwd_len = strlen(cwd);
      |                   ^~~~~~~~~~~
cc1: all warnings being treated as errors   
image

Comment (dennisafa) [reply onvm/onvm_nflib/onvm_nflib.c:1720]: Could you tell me what gcc version this is from? Maybe it's b/c I ran this on an older version of ubuntu.

Comment (WilliamMaa) [reply onvm/onvm_nflib/onvm_nflib.c:1720]: gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0
I think you're right, I'm testing on Ubuntu 20. Maybe I can try this on Ubuntu 18.

Comment (twood02) [reply onvm/onvm_nflib/onvm_nflib.c:1720]: if we are going to merge this it will need to run on ubuntu20's super strict gcc. @sreyanalla  fixed a lot of these errors when porting ONVM so you can check the commit log from that PR if you want to see how to get around it.

Comment (kevindweb) [reply onvm/onvm_nflib/onvm_nflib.c:1720]: @WilliamMaa I just tried compiling and running an example, and it worked fine on Ubuntu 20 with gcc 9.3.0. Is there anything special you did to compile? I didn't get any weird compiler warnings or errors.

Comment (WilliamMaa) [reply onvm/onvm_nflib/onvm_nflib.c:1720]: @kevindweb I'll try again, I don't think I did anything special.
